
import '../local_keys.dart';

Map<String, String> ar = {
  LocalKeys.kName: "الاسم",
  LocalKeys.kPassword: "كلمة المرور",
  LocalKeys.kConfirmPassword: "تاكيد كلمة المرور",
  LocalKeys.kEnterPassword: "ادخل كلمة المرور",
  LocalKeys.kPasswordsDoNotMatch: "كلمة المرور غير مطابقة",
  LocalKeys.kPasswordLength: "يجب ألا تقل كلمة المرور عن 8 أحرف",
  LocalKeys.kPasswordSpaces: "يجب ألا تحتوي كلمة المرور علي أي مسافات",
  LocalKeys.kEmail: "البريد الإلكتروني",
  LocalKeys.kEnterYourEmail: "ادخل بريدك الإلكتروني",
  LocalKeys.kEnterValidEmail: "أدخل بريدًا إلكترونيًا صحيحًا",
  LocalKeys.kPhoneNumber: "رقم الهاتف",
  LocalKeys.kEnterPhoneNumber: "ادخل رقم الهاتف",
  LocalKeys.kValidPhoneNumber: "ادخل رقم هاتف صحيحًا",
  LocalKeys.kRequiredField: "هذا الحقل مطلوب",
  LocalKeys.kPasswordNotValid: "كلمة المرور غير صحيحة",
  LocalKeys.kEmailNotValid: "البريد الإلكتروني غير صحيح",
  LocalKeys.kSend: "أرسِل",
  LocalKeys.kSpecifyGender: "حدد جنس الطفل",
  LocalKeys.kMale: "ولد",
  LocalKeys.kFemale: "بنت",
  LocalKeys.kEditPassword: "عدِّل كلمة المرور",
  LocalKeys.kSave: "احفظ",
  LocalKeys.kCancel: "الغِ",
  LocalKeys.kPleaseAddName: "يُرجى إدخال الاسم",
  LocalKeys.kSelectFromGallery: "اختر من المعرض",
  LocalKeys.kErrorOccured: "حدث خطأ",
  LocalKeys.kBlog: "المقالات",
  LocalKeys.kEduVideos: "فيديوهات تربوية",
  LocalKeys.kTheEduVideos: "الفيديوهات تربوية",
  LocalKeys.kVideo: "فيديو",
  LocalKeys.kEduVideosDesc:
      "تعلم واعرف اكثر من خلال جيل من خلال الفيديوهات التربوية.",
  LocalKeys.kAllSubjects: "كل الموضوعات",
  LocalKeys.kNoBlogs: "لا توجد مقالات",
  LocalKeys.kSubscriptions: "الاشتراكات",
  LocalKeys.kAssistanceAndSupport: "المساعدة والدعم",
  LocalKeys.kAboutTheApp: "عن التطبيق",
  LocalKeys.kSettings: "الإعدادات",
  LocalKeys.kCommonQuestions: "الأسئلة الشائعة",
  LocalKeys.kSubscription: "اشتراك",
  LocalKeys.kOk: "حسنا",
  LocalKeys.kBad: "ضعيف",
  LocalKeys.kForgetPassword: "نسيت كلمة المرور؟",
  LocalKeys.kReports: "التقارير",
  LocalKeys.kNoValuesFound: "لا يوجد قيم!",
  LocalKeys.kSuggestion: "اقتراح",
  LocalKeys.kIssuesAndSuggestions: "المساعدة والدعم",
  LocalKeys.kIssueView: "استعراض الشكوى",
  LocalKeys.kRootMessage:
      "عميلنا العزيز، نأسف لاضطرارنا إلى حجب التطبيق نظرًا إلى قيامكم بانتهاك سياسة الاستخدام إما باستخدام محاكي أو التعديل في نظام الهاتف الخاص بكم على نحو غير آمن.",
  LocalKeys.kSupportAndHelpTopMessage:
      "هل تواجه مشكلة عند استخدامك تطبيق جيل؟\nأو تود مشاركتنا بعض الأفكار؟ أو لديك طلب ما؟\nيسعدنا دائماً التواصل معك وتقديم كل ما يمكننا فعله.",
  LocalKeys.kPeriodFrom: "من",
  LocalKeys.kSerial: "مسلسل",
  LocalKeys.kSeries: "مسلسلات وحلقات",
  LocalKeys.kDiscover: "تعلم ومهارات",
  LocalKeys.kDiscoverWithUsJeelWorld: "اكتشف معنا عالم جيل",
  LocalKeys.kStories: "الحكايات",
  LocalKeys.kOthers: "أخرى",
  LocalKeys.kAlert: "تنبيه",
  LocalKeys.kNetworkConnectionError: "خطأ في الإتصال بالإنترنت",
  LocalKeys.kPleaseAddIssueType: "من فضلك أدخل نوع المشكلة",
  LocalKeys.kPleaseTryAgain: "من فضلك أعد المحاولة",
  LocalKeys.kOpen: "مفتوح",
  LocalKeys.kClose: "مغلق",
  LocalKeys.kTimes: "مرات",
  LocalKeys.kLastStory: "آخر حكاية شاهدها الطفل",
  LocalKeys.kMinuteWatched: "دقيقة مشاهدة",
  LocalKeys.kLastSeries: "آخر مسلسل شاهده الطفل",
  LocalKeys.kAllEpisodes: "كل الحلقات",
  LocalKeys.kEpisode: "حلقة",
  LocalKeys.kAgree: "أوافق",
  LocalKeys.kUnsupportedImageFormat: "ملف صورة غير مدعوم",
  LocalKeys.kChildHasEditedSuccessfully: "تم تعديل حساب الطفل بنجاح",
  LocalKeys.kTryAgain: "حاول مرة أخرى",
  LocalKeys.kWrongAnswer: "لم تكن الإجابة صحيحة",
  LocalKeys.kGood: "جيد",
  LocalKeys.kVeryGood: "جيد جداً",
  LocalKeys.kExcellent: "ممتاز",
  LocalKeys.kAcceptable: "مقبول",
  LocalKeys.kPerfect: "رائع",
  LocalKeys.kSomethingWentWrongPleaseTryAgain:
      "حدث خطأ، يُرجى المحاولة مرة أخرى",
  LocalKeys.kBack: "رجوع",
  LocalKeys.kHoursCount: "عدد الساعات",
  LocalKeys.kNameLengthSmall: "يجب ألا يقل الأسم عن حرفين",
  LocalKeys.kNameLengthsLarge: "يجب ألا يزيد الأسم عن 50 حرف",
  LocalKeys.kPrivacyPolicy: "سياسات الخصوصية",
  LocalKeys.kParentalNotice: "موافقة الوالدين على الاستخدام",
  LocalKeys.kTermsAndConditions: "الشروط والأحكام",
  LocalKeys.kPhoneNumberRegister: "التسجيل عبر رقم الهاتف",
  LocalKeys.kOTPSent: 'أرسلنا لك رمز التحقق',
  LocalKeys.kEnterOTP:
      "من فضلك أدخل الرمز المكون من 6 أرقام الذي أرسلناه في رسالة نصِّية إلى رقم هاتفك ",
  LocalKeys.kOTPIsNotCorrect: "الكود غير صحيح",
  LocalKeys.kOTPNotRecieved: 'إذا لم تستلم الرمز، ',
  LocalKeys.kSendAgainAfter: 'أرسله مجدَّدًا بعد ',
  LocalKeys.kSendAgain: 'أرسله مجدَّدًا!',
  LocalKeys.kMoment: " ثانية",
  LocalKeys.kForgetPasswordNoProblem: 'أنسِيت كلمة المرور؟ لا عليك!',
  LocalKeys.kEnterEmailForReset:
      'من فضلك إدخل البريد الإلكتروني المسجل مسبقاً لدينا.',
  LocalKeys.kNewAccount: "إنشاء حساب جديد",
  LocalKeys.kSignIn: "تسجيل الدخول",
  LocalKeys.kWelcomeInJeel: "أهلًا بك في عالم جيل!",
  LocalKeys.kNewRegisterMethod: 'وسيلة تسجيلٍ جديدة',
  LocalKeys.kChangeToNewRegisterMethod:
      "لأننا نسعى دائمًا لتحسين تجربة مُستَخدمي التطبيق من عائلة جيل، أجرينا بعض التحديثات مؤخرًا على طُرُق تسجيل الدخول. رجاءً أستخدم البريد الإلكتروني وكلمة المرور كوسيلة التسجيل بدلًا من الوسيلة الحالية.",
  LocalKeys.kNewPassword: "كلمة مرور جديدة",
  LocalKeys.kConfirm: "تأكيد",
  LocalKeys.kYourPhoneNumber: 'رقم هاتفك',
  LocalKeys.kEnterPhoneForReset:
      'من فضلك أدخل رقم هاتفك الذي قمت بتسجيل الدخول به مسبقًا',
  LocalKeys.kGo: "انطلق!",
  LocalKeys.kForgetYourPassword: "نَسِيتُ كلمة المرور!",
  LocalKeys.kChooseRegisterMethod: 'اختر طريقة التسجيل',
  LocalKeys.kPreviousRegister: 'هل سجلَّت الدخول بوسيلة أخرى مُسبقًا؟',
  LocalKeys.kDontHaveAccount: "ليس لديك حساب؟! ",
  LocalKeys.kLetsCreateAccount: 'لِنُنشِئ حسابًا جديدًا',
  LocalKeys.kEmailIsNotValid: "عُذرًا! البريد الإلكتروني غير صحيح",
  LocalKeys.kPresentThatEmailAddress: "يبدوا أن بريدك الإلكتروني ",
  LocalKeys.kConnectToOldAccount:
      " مقترن بوسيلة تسجيل دخول قديمة، هل سجَّلت بوسيلة دخول أخرى مُسبَقًا؟",
  LocalKeys.kRegisterNewMethod: "سجلت بوسيلة أخرى",
  LocalKeys.kOtherRegisterMethods: "طرق التسجيل الأخرى",
  LocalKeys.kHelpToEnterEmail: 'لا تقلق، سوف نساعدك لدخول حسابك مجددًا',
  LocalKeys.kchooseOldLoginMethod: 'أختر الطريقة التي قمت بالتسجيل بها مسبقًا',
  LocalKeys.kThroughPhone: "عن طريق رقم الهاتف",
  LocalKeys.kOrRegisterThrough: "'أو التسجيل عبر'",
  LocalKeys.kSkip: "تخطي",
  LocalKeys.kSecurityDoor: "'بوَّابَة الأمان'",
  LocalKeys.kSecurityStep:
      "'هذه خطوة احترازية لنضمن أنَّك أحد الأبوين! اضغط على الأرقام المكتوبة بالأسفل.'",
  LocalKeys.kWelcomeInJeelFamily: 'أهلًا بك في عائلة جيل!',
  LocalKeys.kCancelAccount:
      "'تمَّ إنشاء حسابك بنجاح. هيَّا بنا نتعرَّف عليك وعلى أطفالك!'",
  LocalKeys.kLetsGo: "هيَّا بنا!",
  LocalKeys.kLetsGoInJeel: "هيَّا بنا إلى عالم جيل!",
  LocalKeys.kHaveAccount: "لديك حساب؟ ",
  LocalKeys.kWelcomeBack: 'أهلًا بعودتك',
  LocalKeys.kChooseCountry: "اختر دولتك",
  LocalKeys.kRegisterYouAccept: 'بتسجيلك أنت توافق علي ',
  LocalKeys.kAnd: 'و ',
  LocalKeys.kSearch: "بحث",
  LocalKeys.kExitApp: "الخروج من التطبيق",
  LocalKeys.kChangeRegisterMethod: "تغيير طريقة التسجيل",
  LocalKeys.kBirthYear: "سنة الميلاد",
  LocalKeys.kRegisterError: "خطأ في التسجيل",
  LocalKeys.kRegisterNotComplete: 'نأسف لا يمكنك اتمام التسجيل',
  LocalKeys.kShouldAgreeTerms:
      'لأتمام التسجيل يجب عليك الموافقة على سياسات الاستخدام',
  LocalKeys.kKidAnimOrPic:
      'اختر شخصية كرتونية تُشبِه طفلك أو أضف صورة شخصية له',
  LocalKeys.kHisName: 'ما اسمه؟',
  LocalKeys.kKidName: "اسم الطفل",
  LocalKeys.kAddKidPassword: 'كلمة مرور الطفل',
  LocalKeys.kKidPassword: "كلمة مرور الطفل",
  LocalKeys.kContainFour: "مكونة من 4 أرقام فقط",
  LocalKeys.kOnlyDigits: "مكونة من أرقام فقط",
  LocalKeys.kKidDailyUse: 'مدة الاستخدام اليومي للطفل',
  LocalKeys.kHour: "ساعة",
  LocalKeys.kMinute: "دقيقة",
  LocalKeys.kAdvancedChooses: 'خيارات متقدمة',
  LocalKeys.kAreYou: 'هل أنت',
  LocalKeys.kYears: "سنوات",
  LocalKeys.kFatherMotherName: "اسم الأم/الأب",
  LocalKeys.kRenewalAlert:
      "برجاء اختيار الباقة المناسبه مع العلم ان الباقة تجدد تلقائيا شهريا او سنويا حسب نوع الباقة المختارة و يمكنك الغاء الاشتراك في اي وقت بالدخول علي صفحة الاشتراكات و اختيار الغاء الاشتراك",
  LocalKeys.kNumberIsNotCorrect: 'الرقم غير صحيح، حاول مرة أخرى',
  LocalKeys.kJeelApp: "تطبيق جيل",
  LocalKeys.kFollowKidReports: "متابعة تقارير طفلك!",
  LocalKeys.kFollowKidLearn: "متابعة القيم التي يتعلمها طفلك!",
  LocalKeys.kOkey: "حسنًا!",
  LocalKeys.kStartNow: "ابدأ الآن",
  LocalKeys.kAweasome: "هذا رائع!",
  LocalKeys.kReadyToStartJeelJounary:
      "هل أنت مستعدٌ لتَنطَلِق معنا في رحلةٍ تتشارك فيها أنت وأطفالك الكثير من الأوقات الممتعة! سنُوفِّر لطفلك وقتًا يحظى فيه بالمرح ويُطَوِّر فيه من سُلوكِه مع عائلة جيل.",
  LocalKeys.kTrackKidUse:
      "تابع نشاط طفلك كاملًا على تطبيق جيل؛ كم يقضي من الوقت في استخدام التطبيق؟ ومتى يفتحه؟ وتعرَّف أيضًا إلى نتائج إجاباته على أنشطة كل حلقة يشاهدها.",
  LocalKeys.kReportsForParents:
      "ولكما عزيزي الأب وعزيزتي الأم، نُقدِّم قسم جُسُور؛ بوابتك إلى عالم طفلك. حيث ستجدان محتوىً ثريًّا بالبرامج التربوية بين أيديكما وتقاريرَ مفصَّلة عمَّا يشاهده طفلكما من حلقات وما تحتوي عليه من قيمٍ تربوية.",
  LocalKeys.kExcuse: "عُذرًا",
  LocalKeys.kCantUpdateLoginMethod: "لم نتمكن من تحديث طريقة الدخول",
  LocalKeys.kThankYou: "شكرًا لك!",
  LocalKeys.kLoginMethodUpdated: "تمَّ تغيير طريقة تسجيل الدخول إلى حسابك.",
  LocalKeys.kOtpSentToEmail: "أرسلنا لك رابطًا لإعادة تعيين كلمة المرور على",
  LocalKeys.kCheckYourEmail:
      "تصفَّح بريدك الإلكتروني واتِّبِع الخطوات لإعادة تعيين كلمة مُرورك، ثمَّ سجِّل الدخول مُجدَّدًا بكتابة البريد الإلكتروني وكلمة المرور الجديدة.",
  LocalKeys.kNoAccountWithThisEmail:
      "لا يوجد حساب مسجل بالبريد الإلكتروني المدخل",
  LocalKeys.kCodeSent: "تم إرسال الكود",
  LocalKeys.kNoRecommendations: "لا توجد توصيات",
  LocalKeys.kUserDoesNotExist: "هذا الحساب غير مسجل مسبقاً, قم بالتسجيل أولاً",
  LocalKeys.kEmailAlreadyUsed:
      "البريد الإلكتروني المدخل مستخدم مسبقاً، أدخل بريد إلكتروني جديد",
  LocalKeys.kCredAlreadyUsed: "الحساب المستخدم مسجل مسبقاً، استخدم حساباً أخر",
  LocalKeys.kWeakPassword:
      "كلمة المرور ضعيفة، استخدم كلمة مرور أطول تحتوي علي أرقام ورموز",
  LocalKeys.kPhoneNotConnected: "الهاتف غير متصل بالإنترنت، حاول مرة أخرى",
  LocalKeys.kTooManyRequests: "لقد حاولت الدخول أكثر من مرة، جرب وقتاً لاحق",
  LocalKeys.kNewLogin: "مضت فترة علي أخر تسجيل دخول، سجل الدخول مجددًا",
  LocalKeys.kCantAddKid: "حدث خطأ، لم نتمكن من إضافة الطفل تأكد من إتصالك",
  LocalKeys.kUnsupportedExtension: 'الملف المرفق ليس من نوع مدعوم',
  LocalKeys.kCantAccess: 'تم رفض صلاحيات الوصول للمعرض',
  LocalKeys.kMaleChildCantAccess:
      'لا يُمكنك الدخول إلى تطبيقك المفضل الآن، تحدث مع احد والديك كي يُنشط حسابك',
  LocalKeys.kFemaleChildCantAccess:
      'لا يُمكنك الدخول إلى تطبيقك المفضل الآن، تحدثي مع احد والديك كي يُنشط حسابك',
  LocalKeys.kJoinJeelFamily: "انضم لعائلة جيل",
  LocalKeys.kOr: "أو",
  LocalKeys.kSubscripAndGetDiscount: 'اشترك الآن واحصل على تخفيض',
  LocalKeys.kTo60Percent: ' يصل إلى 60% ',
  LocalKeys.kForLimitedTime: 'لفترة محدودة!',
  LocalKeys.kAccount: 'حساب ',
  LocalKeys.kEditInfo: 'تعديل البيانات',
  LocalKeys.kActivateAccount: "تنشيط الحساب",
  LocalKeys.kDisableAccount: 'تعطيل الحساب',
  LocalKeys.kDeleteAccount: 'حذف الحساب',
  LocalKeys.kWantDeleteAccount: "هل تود حذف حساب ",
  LocalKeys.kAccountWillDeleted: "سيُحذف حساب ",
  LocalKeys.kWithAllReports: " مع كافَّة تقارير الأنشطة والاستخدام.",
  LocalKeys.kDelete2: "حذف",
  LocalKeys.kConfirmAccountSuspend: "تأكيد تعطيل حساب الطفل",
  LocalKeys.kToHisAccount: "إلى حسابه؟",
  LocalKeys.kConfirmSuspend: "هل انت متأكد من منع دخول",
  LocalKeys.kDisable: "تعطيل",
  LocalKeys.kCantAddReview:
      'لا يُمكنك إضافة تقييم جديد، ويمكنك تعديل التقييم السابق من متجر التطبيقات.',
  LocalKeys.kShareText:
      'تطبيق جيل... فائدة ومتعة لأطفالك بلغة عربية فصيحة.\nحمله الآن!\nhttps://jeelapp.app.link/App',
  LocalKeys.kSuspended: "معطل",
  LocalKeys.kActivated: "نشط",
  LocalKeys.kAppNotUsedYet: "لم يستخدم التطبيق بعد",
  LocalKeys.kLastUse: "آخر استخدام: ",
  LocalKeys.kEducationalSection: "القسم التربوي للأباء",
  LocalKeys.kSignOut: "تسجيل الخروج",
  LocalKeys.kShareApp: "مشاركة التطبيق",
  LocalKeys.kReviewApp: "تقييم التطبيق",
  LocalKeys.kAboutJeel: "عن جيل",
  LocalKeys.kJosoorEducationalSection: "جُسُور (القسم التربوي)",
  LocalKeys.kPackageExpired:
      "انتهت باقتك! هيَّا جدِّد اشتراكك... عائلة جيل بانتظارك.",
  LocalKeys.kPackageWillEnd: "ستنتهي الباقة قريبًا في ",
  LocalKeys.kCantAccessCamera: 'تم رفض صلاحيات الوصول للكاميرا',
  LocalKeys.kRateDetails: 'تفاصيل التقييم',
  LocalKeys.kRecommendations: "التوصيات",
  LocalKeys.kNumberOfTimes: "عدد مرات",
  LocalKeys.kSolveActivity: "حل النشاط",
  LocalKeys.kWatching: "المشاهدة",
  LocalKeys.kOverAllEvulation: 'التقييم',
  LocalKeys.kDetails: "التفاصيل",
  LocalKeys.kFavGame: "اللعبة المفضلة",
  LocalKeys.kLastGame: "آخر لعبة لعبها طفلك",
  LocalKeys.kEpisodesDetails: 'تفاصيل الحلقات',
  LocalKeys.kFavRadio: "الراديو المفضل",
  LocalKeys.kLastRadio: "آخر راديو استمع اليه طفلك",
  LocalKeys.kWatchedEpisodes: 'الحلقات التي تم مشاهدتها',
  LocalKeys.kReport: "تقارير",
  LocalKeys.kActivity: "الأنشطة",
  LocalKeys.kUsage: "الاستخدام",
  LocalKeys.kMinutes: "دقائق",
  LocalKeys.kTwoMintues: "دقيقتان",
  LocalKeys.kOneMintues: "دقيقة واحدة",
  LocalKeys.kFavEpisode: "الحلقة المفضل",
  LocalKeys.kFavSeries: "المسلسل المفضل",
  LocalKeys.kFavSong: "الأغنية المفضلة",
  LocalKeys.kFavStory: "الحكاية المفضلة",
  LocalKeys.kLastSong: "آخر أغنية شاهدها طفلك",
  LocalKeys.kOneTime: "مرة واحدة",
  LocalKeys.kTwoTime: "مرتان",
  LocalKeys.kTime: "مرة",
  LocalKeys.kEduPapers: 'الأوراق التربوية',
  LocalKeys.kDevProgram: "البرنامج التطويري",
  LocalKeys.kUntilToday: 'حتي يوم',
  LocalKeys.kEditChildInfo: "تعديل بيانات طفلك",
  LocalKeys.kChildAge: "كم عمره؟",
  LocalKeys.kCopyWrite: "جميع الحقوق محفوظة\n للمالك الحصري شركة روتس انتجريتد",
  LocalKeys.kTheSubscription: "الاشتراك",
  LocalKeys.kBackToApp: "العودة للتطبيق",
  LocalKeys.kChoosePaymentMethod: 'اختر وسيلة الدفع',
  LocalKeys.kThrough: "عبر",
  LocalKeys.kMoreDetails: ' تفاصيل أكثر...',
  LocalKeys.kMonthly: "شهريًا",
  LocalKeys.kYearly: "سنويًا",
  LocalKeys.kWeekly: "أسبوعياً",
  LocalKeys.kReplace: "بدلًا من ",
  LocalKeys.kFawry: "فـــوري",
  LocalKeys.kFawryCode:
      'سنُرسِل لك رمزًا على بريدك أو هاتفك، وكل ما عليك فعله هو التوجه إلى أقرب منفذٍ لفوري وإخباره بالرَّمز ثم دفع قيمة الاشتراك.',
  LocalKeys.kAppleStore: "متجر أبل",
  LocalKeys.kGoogleStore: "متجر جوجل",
  LocalKeys.kWriteCardDetails:
      "اكتُب بيانات البطاقة وادفع في الحال لتستمتع بعالم جيل.",
  LocalKeys.kPaymentCard: "بطاقة الدفع",
  LocalKeys.kMadaCard: "بطاقة مدى باي",
  LocalKeys.kHavePrePaidCard: 'هل لديك بطاقة دفع مسبقة من جيل؟',
  LocalKeys.kDataSecurity:
      "يتم الدَّفع عبر المنصَّات الخاصة بكل وسيلةٍ من الوسائل المُتاحة حفاظًا على سرية بياناتك.",
  LocalKeys.kSubscripInJeel: "الإشتراك في جيل",
  LocalKeys.kPackageAutoRenew: 'تفعيل التجديد التلقائي للباقة',
  LocalKeys.kRenewDate: "تاريخ التجديد",
  LocalKeys.kYouSubscriped: "أنت الآن مشترك في",
  LocalKeys.kRenewPackage: "التجديد المسبق الباقة",
  LocalKeys.kPackageHistory: "سجل الاشتراكات السابقة",
  LocalKeys.kOneAccount:
      'حسابٌ واحدٌ في جيل يفتَح لك عالمًا من المُتَعة والفائدة لك ولأطفالك',
  LocalKeys.kJosoorBlogs: "الاطلاع على مقالات جُسُور التربوية",
  LocalKeys.kDailyReport: "الاطلاع على تقرير الاستخدام اليومي",
  LocalKeys.kEduActivities: "أنشطة تربوية للطفل بعد كل حلقة",
  LocalKeys.kEducationActivities: "نشاط تربوي",
  LocalKeys.kEduActivityHelpYou:
      "سيساعدك النشاط التربوي في توصيل القيمة بشكل أفضل لطفلك.",
  LocalKeys.kEnjoyGamesSongs: "الاستمتاع بجميع الألعاب وأغاني الأطفال",
  LocalKeys.kWatchallEpisodesStories: "مشاهدة جميع المسلسلات والحكايات",
  LocalKeys.kOneAccountThreeKids: "حسابٌ واحد لثلاثة أطفال",
  LocalKeys.kDeadlineDate: "تاريخ الانتهاء",
  LocalKeys.kErrorInCancelation: "حدث خطأ في طلب الإلغاء",
  LocalKeys.kCanAutoRenew:
      "يمكنك تفعيل التجديد التلقائي خلال عملية التجديد ببطاقة الدفع",
  LocalKeys.kWannaToCancelAutoRenew: "هل تود ألغاء التجديد التلقائي",
  LocalKeys.kUndo: "ألغاء",
  LocalKeys.kWillCancelAutoRenew:
      "سيتم الغاء التجديد التلقائي واذا اردت اعادة التفعيا ستضطر لاعادة الاشتراك ",
  LocalKeys.kPaymentError: "خطأ في عملية الدفع",
  LocalKeys.kUnSuccessPayment: "لم تتم عملية الدفع بنجاح",
  LocalKeys.kWhichEqual: "، أي ما يعادل ",
  LocalKeys.kAlmost: " تقريباً",
  LocalKeys.kCardNumberInvalid: "رقم البطاقة غير صحيح",
  LocalKeys.kInternetConnection: "تأكد من اتصالك بالإنترنت",
  LocalKeys.kYouChooseToPay: "لقد اخترت أن تُسدِّد قيمة الاشتراك: ",
  LocalKeys.kEnterDataBelow: 'أدخل البيانات التالية',
  LocalKeys.kConfirmPayment: "تأكيد الدفع",
  LocalKeys.kCVV: "رمز الأمان الثلاثي",
  LocalKeys.kEnterCVV: "أدخل رقم ال cvv في ظهر البطاقة",
  LocalKeys.kNumbetIsInvalid: "الرقم غير صحيح",
  LocalKeys.kEnterCardEndDate: "أدخل تاريخ إنتهاء البطاقة",
  LocalKeys.kCardNumber: "رقم البطاقة",
  LocalKeys.kEnter16NumCard: "أدخل رقم البطاقة المكون من 16 رقم",
  LocalKeys.kPersonalInfoUpdated: "تم تحديث البيانات الشخصية",
  LocalKeys.kErrorInUpdateEmail: "خطأ في تحديث البريد الإلكتروني",
  LocalKeys.kCountry: "البلد",
  LocalKeys.kDad: 'الأب',
  LocalKeys.kMom: "أم",
  LocalKeys.kEnterYourPassword: "أدخل كلمة المرور الخاصة بك",
  LocalKeys.kCurrentPassword: "كلمة المرور الحالية",
  LocalKeys.kPasswordEditError: "خطأ في تعديل كلمة المرور",
  LocalKeys.kPasswordEdited: "تم تغيير كلمة المرور",
  LocalKeys.kChildContentEdited: "تم ضبط محتوى الطفل",
  LocalKeys.kConfirmationMessage: "رسالة تأكيدية",
  LocalKeys.kContentWithMusic: "سيظهر محتوى الحلقات في تطبيق الأطفال بموسيقى.",
  LocalKeys.kContentWithoutMusic:
      "سيظهر محتوى الحلقات في تطبيق الأطفال بدون بموسيقى.",
  LocalKeys.kChildConfig: 'إعدادات محتوى الطفل',
  LocalKeys.kChooseVersion:
      "يتوفر محتوى تطبيق جيل، من مُسلسَلاتٍ وألعابٍ وأغانٍ، بنسختين: نسخة بموسيقى، ونسخة بدون موسيقى.اختر أي نُسخة تريد أن يُشاهدها طفلك:",
  LocalKeys.kNoFile: "لا يوجد ملف حاليًا",
  LocalKeys.kSubscripToEnjoy: "اشترك لتستمتع بباقي محتوى التطبيق",
  LocalKeys.kLetsDevelopOurChild: "هيا نطور طفلنا",
  LocalKeys.kJeelEpisodes: 'حلقات جيل',
  LocalKeys.kJeelValues: 'قيم جيل',
  LocalKeys.kSongs: "أغاني",
  LocalKeys.kJeelRadio: "راديو جيل",
  LocalKeys.kCategories: "أقسام",
  LocalKeys.kEnjoyWithYourChild:
      'من بين كل أبطال عالم جيل، أنت بطل طفلك الحقيقي! استمتع معه برحلة تربوية رائعة، سيُرشدك جُسُور خلالها بأوراق تربوية تشرح لك قيم الحلقات، وبرامج تطويرية تعطيك خطوات عملية لتعزيز القيم والسلوكيات؛ كما سيُعرِّفك على المسلسلات والأبطال المُفضلين لطفلك كي تُحدثه عنهم وتناقش معه حلقاتهم.وتذكَّر، يُحب طفلك دومًا قضاء وقته مع بطله الحقيقي!',
  LocalKeys.kEpisodesInculdeValues: 'حلقات تتضمن قيمة ',
  LocalKeys.kJosoor: "جُسُور",
  LocalKeys.kShowEduValues: 'يمكنك البحث من خلال القيم او الحلقات',
  LocalKeys.kStartYourJounary: 'ابدأ رحلتك!',
  LocalKeys.kSong: "أغنية",
  LocalKeys.kDay: "يوم",
  LocalKeys.kHours: "ساعات",
  LocalKeys.kTheDay: "اليوم",
  LocalKeys.kLastResponse: "أخر رد",
  LocalKeys.kLastResponseFrom: "أخر رد منذ",
  LocalKeys.kMessage: "رسالة",
  LocalKeys.kSupportTeam: "فريق الدعم",
  LocalKeys.kProblemRecieved: "تم استلام الشكوى، وسوف نرد عليكم في أقرب وقت.",
  LocalKeys.kProblemType: "نوع المشكلة",
  LocalKeys.kAddAddressAndTitleOfRequest: "أدخل عنوان ووصف للطلب الخاص بك",
  LocalKeys.kAppBetterWithYou: "تطبيقنا أفضل بكم!",
  LocalKeys.kWeSeekItBetter:
      'نسعى لجعل تجربتكم في تطبيق جيل مثالية وممتعة، ويُسعدنا أن ترسلوا إلينا أي مشكلات تواجهكم أو اقتراحات تحبون أن تروها في تطبيقنا.',
  LocalKeys.kMessageAddress: 'عنوان الرسالة',
  LocalKeys.kMessageReason: 'سبب الرسالة',
  LocalKeys.kMessageDetails: 'نص الرسالة',
  LocalKeys.kWriteHere: "اكتب هنا",
  LocalKeys.kAttachPic: 'أرفق صورة',
  LocalKeys.kSendMessage: "إرسال",
  LocalKeys.kProblem: "شكوى",
  LocalKeys.kNewChild: "طفل جديد",
  LocalKeys.kDeleteConfirmationTitleArabic: 'هل أنت متأكد من إلغاء حسابك؟',
  LocalKeys.kDeleteConfirmationTitleEnglish:
      'Are you sure you want to delete your account?',
  LocalKeys.kDeleteConfirmationTextArabic:
      'عند إلغاء حسابك، ستُحذَف جميع بيانات الحساب، بما في ذلك بياناتك وبيانات أطفالك وبيانات الاستخدام، ولن تتمكن من الدخول إلى الحساب مرة أخرى، وستحتاج إلى تسجيل حساب جديد كي تستخدم التطبيق ثانيةً.',
  LocalKeys.kDeleteConfirmationTextEnglish:
      'By deleting your account, all your data will be removed, including your account information, children\'s information, and usage data. After deletion, You will no longer be able to log in to this account and you will need to create a new account to use the app.',
  LocalKeys.kEnteredWrongPasswordBro:
      'أدخلت كلمة مرور خاطئة يا صديقي. اسأل أحد والديك عن الكلمة الصحيحة',
  LocalKeys.kEnteredWrongPasswordGirl:
      'أدخلت كلمة مرور خاطئة يا صديقتي. اسألي أحد والديك عن الكلمة الصحيحة',
  LocalKeys.kReadWithJeel: 'اقرأ مع جيل',
  LocalKeys.kJeelGames: 'ألعاب جيل',
  LocalKeys.kNoGames: 'لا توجد ألعاب حاليا',
  LocalKeys.kNoBooks: 'لا يوجد كتب حاليا',
  LocalKeys.kNoRadio: 'لا يوجد محتوى راديو حاليا',
  LocalKeys.kJeelSeries: "مسلسلات وحلقات جيل",
  LocalKeys.kJeelSongs: 'أغانى جيل',
  LocalKeys.kJeelChants: 'أناشيد جيل',
  LocalKeys.kTimeOutSeeYouTomorrowBoy:
      "لقد انتهى وقتك المحدد اليوم، اراك غدا يا صديقي",
  LocalKeys.kTimeOutSeeYouTomorrowGirl:
      "لقد انتهى وقتك المحدد اليوم، اراكَ غدا يا صديقتي",
  LocalKeys.kHowDoYouPreferAppContent: "كيف تفضل محتوى التطبيق؟",
  LocalKeys.kEnterFourNumbers: "أدخل أربعة أرقام",
  LocalKeys.kCanNotPay: "لم تتمكن من الدفع",
  LocalKeys.kCongratulations: "تهــانيـــنا",
  LocalKeys.kNoInternetConnection: "لا يوجد اتصال بالأنترنت",
  LocalKeys.kConnectionFailed: "خطأ في الاتصال",
  LocalKeys.kPaymentSuccess: "تم الدفع بنجاح",
  LocalKeys.kWrongCredentials: "خطأ في البيانات",
  LocalKeys.kCardInfo: "معلومات البطاقة",
  LocalKeys.kScanCard: "امسَح الرمز المُربَّع على البطاقة",
  LocalKeys.kOrEnterSubscriptionCode: "أو أدخل رمز الاشتراك هنا",
  LocalKeys.kSubscriptionCode: "رمز الاشتراك",
  LocalKeys.kWelcomeInJeelFamilyPrePaidSubscription:
      "أهلًا بك في عائلة جيل! ! أنت الآن مشترك عبر البطاقة مُسبَقة الدفع من جيل.",
  LocalKeys.kLetsDiscoverJeelWorld: "هيَّا بنا نستكشف عالم جيل!",
  LocalKeys.kEnterSubscriptionCode: "أدخل كود الاشتراك",
  LocalKeys.kWrongSubscriptionCode: "للأسف! رمز الاشتراك خاطئ. تأكد من الرمز",
  LocalKeys.kSorryNoAvailableBooks: "عفواً ، لا توجد كتب متاحة حالياً",
  LocalKeys.kPrepaidJeelCard: "البطاقة مُسبَقة الدفع من جيل",
  LocalKeys.kThroughMadaCard: " عبر بطاقة مدى.",
  LocalKeys.kCardExpired: "انتهت صلاحية هذة البطاقة",
  LocalKeys.kKidInvalidAge: "سن الطفل لا يمكن أن يكون صفر",
  LocalKeys.kTotalWeekUsageTime: "مدة الاستخدام الكلية هذا الأسبوع",
  LocalKeys.kAverageDailyUse: "متوسط الاستخدام اليومي",
  LocalKeys.kChildDayUse: 'استخدام طفلك على مدار اليوم',
  LocalKeys.kLastSevenDaysChildActivitiesMessage:
      "يبدو أن طفلك لم يمارس في آخر سبعة أيام شيئا من أنشطة مسلسلات وحلقات! شجع طفلك على إجابة أنشطة الحلقات التي يشاهدها ليستفيد بها على النحو الأمثل.",
  LocalKeys.kLastSevenDaysChildRadioWatchingMessage:
      "يبدو أن طفلك لم يشاهد في آخر سبعة أيام شيئا من محتوي راديو جيل! شجع طفلك على التجول في جميع أقسام التطبيق ليستفيد بها على النحو الأمثل.",
  LocalKeys.kLastSevenDaysChildSeriesWatchingMessage:
      "يبدو أن طفلك لم يشاهد في آخر سبعة أيام شيئا من محتوي مسلسلات وحلقات! شجع طفلك على التجول في جميع أقسام التطبيق ليستفيد بها على النحو الأمثل.",
  LocalKeys.kLastSevenDaysChildGamesWatchingMessage:
      "يبدو أن طفلك لم يلعب في آخر سبعة أيام! شجع طفلك على التجول في جميع أقسام التطبيق ليستفيد به على النحو الأمثل.",
  LocalKeys.kLastSevenDaysChildDiscoverWatchingMessage:
      "يبدو أن طفلك لم يشاهد في آخر سبعة أيام شيئا من محتوى تعلم ومهارات! شجع طفلك على التجول في جميع أقسام التطبيق ليستفيد به على النحو الأمثل.",
  LocalKeys.kLastSevenDaysChildSongsWatchingMessage:
      "يبدو أن طفلك لم يشاهد في آخر سبعة أيام شيئا من محتوى الأغاني! شجع طفلك على التجول في جميع أقسام التطبيق ليستفيد به على النحو الأمثل.",
  LocalKeys.kLastSevenDaysChildStoriesWatchingMessage:
      "يبدو أن طفلك لم يشاهد في آخر سبعة أيام شيئا من محتوى الحكايات! شجع طفلك على التجول في جميع أقسام التطبيق ليستفيد به على النحو الأمثل.",
  LocalKeys.kTheSeries: "مسلسلات وحلقات",
  LocalKeys.kTheStories: "الحكايات",
  LocalKeys.kTheChants: "أناشيد",
  LocalKeys.kTheSongs: "الأغاني",
  LocalKeys.kAddReply: "أضف رد",
  LocalKeys.kEditAccountInfo: 'تعديل بيانات الحساب',
  LocalKeys.kOldPassword: "كلمة مرورك القديمة",
  LocalKeys.kIntellectualPropertyNotice: "الملكية الفكرية",
  LocalKeys.kDisclaimerOfLiability: "إخلاء المسؤولية",
  LocalKeys.kToGames: "إلى الألعاب",
  LocalKeys.kRetryPlayAndLearn: "إعادة العب وتعلم",
  LocalKeys.kContinueWatching: "أكمل المشاهدة",
  LocalKeys.kChangeLang: "تغيير لغة التطبيق",
  LocalKeys.kChooseLang: "من فضلك أختر لغة التطبيق التي تريدها.",
  LocalKeys.kArabic: "اللغة العربية",
  LocalKeys.kEnglish: "English",
  LocalKeys.kSeriesActivities: "أنشطة مسلسلات وحلقات",
  LocalKeys.kStoriesActivities: "أنشطة الحكايات",
  LocalKeys.kDiscoverActivities: "أنشطة تعلم ومهارات",
  LocalKeys.kChantsActivities: "أنشطة الأناشيد",
  LocalKeys.kSongsActivities: "أنشطة الأغاني",
  LocalKeys.kPuzzle: "التركيب",
  LocalKeys.kPainting: "التلوين",
  LocalKeys.kDragAndDrop: "السحب والافلات",
  LocalKeys.kPlayAndLearn: "إلعب وتعلم",
  LocalKeys.kYourChildrenReports: "تقارير أطفالك",
  LocalKeys.kYourChildren: 'أطفالك',
  LocalKeys.kEditChildrenInfo: "تعديل بيانات أطفالك",
  LocalKeys.kWatchs: "شاهد",
  LocalKeys.kMoreValues: "قيم أخرى",
  LocalKeys.kWatchMore: "شاهد المزيد",
  LocalKeys.kWatchAllEpisodes: "شاهد جميع قيم الحلقات",
  LocalKeys.kSelectCats: "إختر  من تصنيفات جيل لتشاهد القيم بداخلها",
  LocalKeys.kView: "مشاهدة",
  LocalKeys.kAllActivityCount: "نشاط",
  LocalKeys.kWelcomeTo: "مرحبا بك، ",
  LocalKeys.kInArticle: "في المقالات",
  LocalKeys.kYouWillFndMoreArticles:
      "ستجد الكثير من المقالات التي ستنال أعجابك، متأكدون من ذلك.",
  LocalKeys.kSubscribeToPlan: "أشترك في خططنا الشهرية، شاهد المزايا.",
  LocalKeys.kSubscribeBenefits: "مزايا الإشتراك",
  LocalKeys.kEditing: "تعديل",
  LocalKeys.kChooseChildYouWantEditHisData:
      "أختر طفلك الذي تريد تعديل بياناته.",
  LocalKeys.kAddAnotherChild: "أضافة طفل أخر",
  LocalKeys.kAddYourChildDetails:
      "من فضلك، أضف بيانات طفلك لتخصيص التجربة له وللحصول علي تحكم أكبر.",
  LocalKeys.kTheMinutes: "الدقائق",
  LocalKeys.kModified: "تم التعديل",
  LocalKeys.kChangeImage: "تغير الصورة",
  LocalKeys.kTakeImageFromCamera: "ألتقط صورة من الكاميرا",
  LocalKeys.kUploadImageForChild: "رفع صورة شخصية لطفلك",
  LocalKeys.kYouCanAddPasswordAndControlTheDuration:
      "يمكنك اضافة كلمة مرور والتحكم في مدة الأستخدام اليومي للطفل.",
  LocalKeys.kAddYourChildNow: "أضف طفلك الأن",
  LocalKeys.kAddNewChild: "أضافة طفل جديد",
  LocalKeys.kAddYourChildInfo: "أضافة بيانات طفلك",
  LocalKeys.kSelectPictureOrUploadPicture:
      "أختر صورة لطفلك أو قم برفع صورة شخصية له",
  LocalKeys.kItIsBoy: "أنه ولد",
  LocalKeys.kSheIsGirl: "أنها بنت",
  LocalKeys.kUploadpictureForChild: "رفع صورة للطفل",
  LocalKeys.kFatherInfo: "بيانات الأب",
  LocalKeys.kMotherInfo: "بيانات الأم",
  LocalKeys.kSideMenu: "القائمة",
  LocalKeys.kSubscriptionEnded: "أنتهت خطتك ، يمكنك الأشتراك مجدداً.",
  LocalKeys.kToFinishPlan: " لإنتهاء اشتراكك.",
  LocalKeys.kRemain: "باقي",
  LocalKeys.kSeePlan: "تفاصيل الإشتراك",
  LocalKeys.kGoBack: "رجوع",
  LocalKeys.kContentControl: "التحكم في المحتوى",
  LocalKeys.kEduJosoorParent: "القسم التربوي للأباء (جسور)",
  LocalKeys.kEduJosoorParentBenefits: "مميزات القسم التربوي للأباء ( جسور )",
  LocalKeys.kEduJosoorParentHero:
      "من بين أبطال جيل، أنت البطل الحقيقي لطفلك تعرف علي مزايا جسور.",
  LocalKeys.kNext: "التالي",
  LocalKeys.kYouSelected: "لقد إخترت، ",
  LocalKeys.kAllFieldRequired: "جميع الحقول مطلوبة",
  LocalKeys.kSixPm: "6 م",
  LocalKeys.kSixAm: "6 ص",
  LocalKeys.kTwelvePm: "12 م",
  LocalKeys.kTwelveAm: "12 ص",
  LocalKeys.kSubscribeNow: "اشترك الآن",
  LocalKeys.kYouSureLogout: "هل أنت متأكد من تسجيل الخروج؟",
  LocalKeys.kWaitWantToLogout: "لحظة من فضلك، هل تريد تسجيل الخروج!",
  LocalKeys.kYesLogout: "نعم، تسجيل خروج",
  LocalKeys.kNoThankyou: "لا، شكرا",
  LocalKeys.kCloseWindow: "إغلاق النافذة",
  LocalKeys.kMainValue: "قيمة أساسية",
  LocalKeys.kMainScreen: "الرئيسية",
  LocalKeys.kSubValue: "قيمة فرعية",
  LocalKeys.kInsideValueEduDev:
      "داخل كل قيمة حلقات وأوراق تربوية وبرنامج تطويري٫",
  LocalKeys.kLearnValueDev: "أعرف أكثر عن القيمة، وطورها لطفلك",
  LocalKeys.kWhatValue: "ماهي قيمة",
  LocalKeys.kLearnedEpisode: "المستفادة  من هذه الحلقة؟",
  LocalKeys.kHoldValue: "التي تحمل قيمة",
  LocalKeys.kEpisodeIntro: "مقدمة المسلسل",
  LocalKeys.kHereAppears: "هنا يظهر اهم",
  LocalKeys.kYourChildHasSolved: "التي قام طفلك بحلها",
  LocalKeys.kActivityDetails: "تفاصيل النشاط",
  LocalKeys.kChooseGames: "رائع، إختر الآن من الإلعاب ",
  LocalKeys.kTypeOfCreativity: "ماهي قيمة الأبداع المستفادة  من هذه الحلقة؟",
  LocalKeys.kOverallEvaluation: "تقييم العام للنشاط",
  LocalKeys.kEducationalActivity: "نشاط تربوي",
  LocalKeys.kTheEducationalActivityWillHelpYou:
      "سيساعدك النشاط التربوي في توصيل القيمة بشكل أفضل لطفلك.",
  LocalKeys.kViews: "مشاهدات",
  LocalKeys.kHereShowViews: "هنا يظهر المشاهدات/*",
  LocalKeys.kYourChildHasWatched: "التي شاهدها طفلك بالتفصيل.",
  LocalKeys.kYourChildHasPracticed: "التي مراسها طفلك بالتفصيل.",
  LocalKeys.kAll: "جميع",
  LocalKeys.kGames: "ألعاب جيل",
  LocalKeys.kListening: "استماع",
  LocalKeys.kTheRadio: "الراديو",
  LocalKeys.kHereShownListeningRadioYouChildHasHeard:
      "هنا يظهر استماع الراديو التي سمعها طفلك بالتفصيل",
  LocalKeys.kViewDetails: "تفاصيل المشاهدات",
  LocalKeys.kWatchVideo: "شاهد الفيديو",
  LocalKeys.kSubscribeNowAndEnjoy: "اشترك الآن وتمتع بمزايا تطبيق جيل!",
  LocalKeys.kBySubScribeToJeel:
      "من خلال أشتراك في جيل سيفتح عالم المتعة والفائدة لك ولأطفالك.",
  LocalKeys.kInvestInYourChild: "أستثمر في أبنائك لمستقبل أفضل لهم.",
  LocalKeys.kSubscribeInEducationalSection:
      "اشترك في التطبيق التربوي الأفضل لأبنائك",
  LocalKeys.kSelect: "قمت بأختيار",
  LocalKeys.kYouWillPay: "ستقوم بالدفع",
  LocalKeys.kForAWeek: "لمدة اسبوع",
  LocalKeys.kForAMonth: "لمدة شهر",
  LocalKeys.kForAYear: "لمدة عام",
  LocalKeys.kChangePackage: "تغير الباقة",
  LocalKeys.kSelectPayMethod: "اختر طريقة الدفع",
  LocalKeys.kSelectPayMethodSuitedForYou:
      "من فضلك أختر طريقة الدفع المناسبة لك.",
  LocalKeys.kPayNow: "ادفع الأن",
  LocalKeys.kYearlyPackage: "الباقة السنوية",
  LocalKeys.kMonthlyPackage: "الباقة الشهرية",
  LocalKeys.kWeeklyPackage: "الباقة الأسبوعية",
  LocalKeys.kAbout: "عبر",
  LocalKeys.kEnjoyGames: 'استمتع بأحدث ألعاب جيل.',
  LocalKeys.kLearnEnjoyGames: 'تعلم وإستمتع مع ألعاب جيل.',
  LocalKeys.kListenSongsAnashees: 'تعلم وغني مع أناشيد جيل.',
  LocalKeys.kSongsAnasheed: 'استمتع بأغاني جيل.',
  LocalKeys.kRadioJeelEnjoy: 'استمتع براديو جيل.',
  LocalKeys.kLearnEnjoyRadio: 'تعلم وغني مع راديو جيل.',
  LocalKeys.kSelectedMethod: "الطريقة المختارة",
  LocalKeys.kChoose: "اختر",
  LocalKeys.kChoosePackage: "اختر الباقة",
  LocalKeys.kAutomaticallyRenewed: "سيتم تجديد الباقة تلقائيا",
  LocalKeys.kSelectSuitedPackage: "أختر الباقة التي تناسبك!",
  LocalKeys.kPleaseSelectFromMultiplePackage:
      "من فضلك أختر من ضمن الباقات المتعددة التي نوفرها لك.",
  LocalKeys.kYourSubscription: "الاشتراكات الخاصة بك",
  LocalKeys.kSubscripThrough: "إشتركت من خلال",
  LocalKeys.kYouSubscripedSuccessfuly: "تم الأشتراك بنجاح، بالباقة السنوية",
  LocalKeys.kWishHappyExperience: "نتمني لك تجربة ممتعة لك ولأطفالك.",
  LocalKeys.kHomePage: "الصفحة الرئيسية",
  LocalKeys.kSeriesEpisodes: "حلقات المسلسل",
  LocalKeys.kSelectEpisodeShowValue:
      "إضغط علي الحلقة لمشاهدة القيم التي تقدمها.",
  LocalKeys.kThePackageRenewWhenTheCurrentExpired:
      "سيتم تجديد الباقة عند إنتهاء مدة الباقة الحالية بتاريخ",
  LocalKeys.kSubscribeWithUs: "سجل معنا",
  LocalKeys.kChooseTypeYouPrefer: "إختر النسخة التي تفضلها للمحتوي ",
  LocalKeys.kWeHaveTwoTypeOfContent:
      "يتوفر لدينا نسختين للمحتوي بموسيقي وبدون موسيقي.",
  LocalKeys.kWithMusic: "بموسيقي",
  LocalKeys.kWithOutMusic: "بدون موسيقي",
  LocalKeys.kChildApp: "تطبيق الطفل",
  LocalKeys.kCreateAccount: "إنشاء حساب",
  LocalKeys.kSimpleStepsToJoinJeel: "خطوات بسيطة تفصلك للدخول الي عالم جيل.",
  LocalKeys.kStepOne: "الخطوة الأولي",
  LocalKeys.kStepTwo: "الخطوة الثانية",
  LocalKeys.kLastStep: "الخطوة الإخيرة",
  LocalKeys.kSearchWithWords: "البحث بالكتابة",
  LocalKeys.kWelcomeInJeelWorld:
      "مرحبا بك مجدداً في عالم جيل من فضلك إدخل بياناتك.",
  LocalKeys.kChangeUser: "تغيير المستخدم",
  LocalKeys.kGreatLoginSuccessfuly: "رائع، تم التسجيل بنجاح",
  LocalKeys.kLetsGoToParentApp:
      "قم الإن بالدخول لتطبيق الوالدين بإضافة إطفالك.",
  LocalKeys.kYourAccountsInJeel: "حساباتك في جيل",
  LocalKeys.kParentAccount: "حساب الوالدين",
  LocalKeys.kChildAccount: "حسابات الطفل",
  LocalKeys.kWelcome: "مرحبا",
  LocalKeys.kMore: "المزيد",
  LocalKeys.kChangeCategoris: "تغيير التصنيفات",
  LocalKeys.kEnjoyRead: 'إستمتع بإحدث كتب جيل.',
  LocalKeys.kLearnEnjoyRead: 'تعلم وإستمتع مع كتب جيل.',
  LocalKeys.kShowLess: "أقل",
  LocalKeys.kShowMore: "المزيد",
  LocalKeys.kWhatNext: "ما التالي؟",
  LocalKeys.kWantToEnjoyJeel:
      'هل تريد الإستمتاع بباقي الحلقات والآنشطة؟ إطلب من ولي إمرك الإشتراك في التطبيق',
  LocalKeys.kWantToEnjoyJeelParent: 'هل تريد الإستمتاع بباقي الحلقات والآنشطة؟',
  LocalKeys.kWantToSubscribeJoinJeelParent:
      'هل تود الاشتراك و الانضمام لعائلة جيل؟',
  LocalKeys.kPages: 'الصفحات',
  LocalKeys.kPayment: "الدفع",
  LocalKeys.kSubscriptionPolicy: "تخضع الاشتراكات الى ",
  LocalKeys.kSubscriptionTerms: "سياسة الخصوصية",
  LocalKeys.kChildHasDeleted: "تم حذف الحساب بنجاح",
  LocalKeys.kLoading: "تحميل...",
  LocalKeys.kNoActivitiesFound: "لم يتم العثور علي أي أنشطة",
  LocalKeys.kPractice: "ممارسة",
  LocalKeys.kPractices: "ممارسات",
  LocalKeys.kAllSections: "الاقسام",
  LocalKeys.kSummaryUsageTime: "ملخص اوقات الاستخدام",
  LocalKeys.kEducationSystem: "القسم التربوي",
  LocalKeys.kValueCreativity: "قيمة الابداع",
  LocalKeys.kEpisodeIncludeActivity: "حلقة تتضمن قيمة الأبداع",
};
