
import '../local_keys.dart';

Map<String, String> en = {
  LocalKeys.kName: "Name",
  LocalKeys.kPassword: "Password",
  LocalKeys.kConfirmPassword: "Confirm Password",
  LocalKeys.kEnterPassword: "Enter Password",
  LocalKeys.kPasswordsDoNotMatch: "Passwords doesn't match",
  LocalKeys.kPasswordLength: "Password Should not be less than 8 letters",
  LocalKeys.kPasswordSpaces: "Password Should not contain any Spaces",
  LocalKeys.kEmail: "E-mail",
  LocalKeys.kEnterYourEmail: "Enter Your Email",
  LocalKeys.kEnterValidEmail: "Enter valid email",
  LocalKeys.kPhoneNumber: "Phone Number",
  LocalKeys.kEnterPhoneNumber: "Enter Phone Number",
  LocalKeys.kValidPhoneNumber: "Enter valid phone number",
  LocalKeys.kRequiredField: "This Field is required",
  LocalKeys.kPasswordNotValid: "Incorrect Password",
  LocalKeys.kEmailNotValid: "Incorrect E-mail",
  LocalKeys.kSend: "Send",
  LocalKeys.kSpecifyGender: "Specify Gender",
  LocalKeys.kMale: "Boy",
  LocalKeys.kFemale: "Girl",
  LocalKeys.kEditPassword: "Edit Password",
  LocalKeys.kSave: "Save",
  LocalKeys.kCancel: "Cancel",
  LocalKeys.kPleaseAddName: "Please Enter the Name",
  LocalKeys.kSelectFromGallery: "Choose from Gallery",
  LocalKeys.kErrorOccured: "Error occurred",
  LocalKeys.kBlog: "Articles",
  LocalKeys.kEduVideos: "Educational videos",
  LocalKeys.kTheEduVideos: "The Educational videos",
  LocalKeys.kVideo: "Videos",
  LocalKeys.kEduVideosDesc: "Learn more about Jeel through educational videos.",
  LocalKeys.kAllSubjects: "All Subjects",
  LocalKeys.kNoBlogs: "No Articles",
  LocalKeys.kSubscriptions: "Subscriptions",
  LocalKeys.kAssistanceAndSupport: "Help and Support",
  LocalKeys.kAboutTheApp: "About Jeel",
  LocalKeys.kSettings: "Settings",
  LocalKeys.kCommonQuestions: "FAQ",
  LocalKeys.kSubscription: "Subscriptions",
  LocalKeys.kOk: "OK",
  LocalKeys.kBad: "Bad",
  LocalKeys.kForgetPassword: "Forget Password?",

  LocalKeys.kReports: "Reports",
  LocalKeys.kNoValuesFound: "No Values Found!",
  LocalKeys.kSuggestion: "Suggestion",
  LocalKeys.kIssuesAndSuggestions: "suggestions and complaints",
  LocalKeys.kIssueView: "View Complaint",
  LocalKeys.kRootMessage:
      "Dear Customer, We are Sorry that we had to block the application because you broke the (Usage Terms and Conditions) Rules, Either by using an emulator or Modify your phone System Unsafely.",
  LocalKeys.kSupportAndHelpTopMessage:
      "Do you Have any problem while using Jeel Application?\n Or Would you like to share some suggestions? Or Do you have any Request?\n We are always delighted to contact you and offer you our assistance.",
  LocalKeys.kPeriodFrom: "From",
  LocalKeys.kSerial: "Serial",
  LocalKeys.kSeries: "Series",
  LocalKeys.kDiscover: "Learning & skills",
  LocalKeys.kDiscoverWithUsJeelWorld: "Discover with us Jeel World",
  LocalKeys.kStories: "Stories",
  LocalKeys.kOthers: "Others",
  LocalKeys.kAlert: "Alert",
  LocalKeys.kNetworkConnectionError: "Network Connection Error",
  LocalKeys.kPleaseAddIssueType: "Please Enter The type of issue",
  LocalKeys.kPleaseTryAgain: "Please Try Again",
  LocalKeys.kOpen: "Open",
  LocalKeys.kClose: "Close",
  LocalKeys.kTimes: "Times",
  LocalKeys.kLastStory: "Last Watched Story by your child",
  LocalKeys.kMinuteWatched: "Minute of Watching",
  LocalKeys.kLastSeries: "Last Watched Series by your Child",
  LocalKeys.kAllEpisodes: "All Episodes",
  LocalKeys.kEpisode: "Episode",
  LocalKeys.kAgree: "Agree",
  LocalKeys.kUnsupportedImageFormat: "Unsupported Image Format",
  LocalKeys.kChildHasEditedSuccessfully:
      "Child's Account has been Edited Successfully",
  LocalKeys.kTryAgain: "Try Again",
  LocalKeys.kWrongAnswer: "Wrong Answer",
  LocalKeys.kGood: "Good",
  LocalKeys.kVeryGood: "Very Good",
  LocalKeys.kExcellent: "Excellent",
  LocalKeys.kAcceptable: "Acceptable",
  LocalKeys.kPerfect: "Perfect",
  LocalKeys.kSomethingWentWrongPleaseTryAgain:
      "Something Wrong, Please Try again",
  LocalKeys.kBack: "Back",
  LocalKeys.kHoursCount: "Number of Hours",
  LocalKeys.kNameLengthSmall: "Name should not be less than 2 letters",
  LocalKeys.kNameLengthsLarge: "Name should not be more than 50 Letters",
  LocalKeys.kPrivacyPolicy: "Privacy Policy",
  LocalKeys.kParentalNotice: "Parents Approval for Usage",
  LocalKeys.kTermsAndConditions: "Terms and Conditions",
  LocalKeys.kPhoneNumberRegister: "Register by Phone Number",
  LocalKeys.kOTPSent: 'We Sent You a Verification Code',
  LocalKeys.kEnterOTP:
      "Please Enter the code made up of 6 numbers that we sent to your phone number",
  LocalKeys.kOTPIsNotCorrect: "Wrong Verification Code",
  LocalKeys.kOTPNotRecieved: 'If you did not receive the Code, ',
  LocalKeys.kSendAgainAfter: ' Resend it!',
  LocalKeys.kSendAgain: 'Send Again!',
  LocalKeys.kMoment: "Second ",
  LocalKeys.kForgetPasswordNoProblem: 'Forget your Password? No Worries!',
  LocalKeys.kEnterEmailForReset:
      "Please Enter your E-mail that you signed up with",
  LocalKeys.kNewAccount: "Create New Account",
  LocalKeys.kSignIn: "Sign In",
  LocalKeys.kWelcomeInJeel: "Welcome to Jeel World",
  LocalKeys.kNewRegisterMethod: 'New Registration Method',
  LocalKeys.kChangeToNewRegisterMethod:
      "As we always pursue ways to improve the experience of all users in Jeel family, we created a new update on our sign in methods. Please use your E-mail and password as a way to sign up instead of the current way.",
  LocalKeys.kNewPassword: "New Password",
  LocalKeys.kConfirm: "Confirm",
  LocalKeys.kYourPhoneNumber: 'Your Phone Number',
  LocalKeys.kEnterPhoneForReset:
      'Please enter the phone number that you registered before',
  LocalKeys.kGo: "Lets Go!",
  LocalKeys.kForgetYourPassword: "Forget Password!",
  LocalKeys.kChooseRegisterMethod: 'Choose Registration Way',
  LocalKeys.kPreviousRegister: 'Have you used another way to register before?',
  LocalKeys.kDontHaveAccount: "Don't Have an Account? ",
  LocalKeys.kLetsCreateAccount: "Make A New Account!",
  LocalKeys.kEmailIsNotValid: "Sorry, Incorrect E-mail!",
  LocalKeys.kPresentThatEmailAddress: "Seems like your E-mail ",
  LocalKeys.kConnectToOldAccount:
      " Is connected to another account, have you used another sign in method before",
  LocalKeys.kRegisterNewMethod: "Used a different registration method before?",
  LocalKeys.kOtherRegisterMethods: "Other Register Methods",
  LocalKeys.kHelpToEnterEmail:
      "Don't Worry!, We will help you enter your account again",
  LocalKeys.kchooseOldLoginMethod: 'Choose the same way you registered before',
  LocalKeys.kThroughPhone: "by Phone Number",
  LocalKeys.kOrRegisterThrough: "'Or Registration by'",
  LocalKeys.kSkip: "Skip",
  LocalKeys.kSecurityDoor: "The safety Gate",
  LocalKeys.kSecurityStep:
      "This is a crucial step to make sure you are one of the Parents! Click on the numbers listed.",
  LocalKeys.kWelcomeInJeelFamily: "Welcome to Jeel Family",
  LocalKeys.kCancelAccount:
      "Your Account has been created successfully, Lets get to know you and your children",
  LocalKeys.kLetsGo: "Lets Go!",
  LocalKeys.kLetsGoInJeel: "Lets Go to Jeel World!",
  LocalKeys.kHaveAccount: "Do You Have an Account? ",
  LocalKeys.kWelcomeBack: 'Welcome Back',
  LocalKeys.kChooseCountry: "Choose your Country",
  LocalKeys.kRegisterYouAccept: "By your Registration, you have agreed to ",
  LocalKeys.kAnd: "And ",
  LocalKeys.kSearch: "Search",
  LocalKeys.kExitApp: "Exit App",
  LocalKeys.kChangeRegisterMethod: "Change Registration Method",
  LocalKeys.kBirthYear: "Birth Year",
  LocalKeys.kRegisterError: " Registration Error",
  LocalKeys.kRegisterNotComplete:
      'Sorry, You can not complete your Registration',
  LocalKeys.kShouldAgreeTerms:
      "To complete your registration you must agree to the terms and conditions",
  LocalKeys.kKidAnimOrPic:
      "Choose an avatar that matches your child or add a photo for him",
  LocalKeys.kHisName: "What is his name?",
  LocalKeys.kKidName: "The Child's Name",
  LocalKeys.kAddKidPassword: "Add Child's Password",
  LocalKeys.kKidPassword: "Child's Password",
  LocalKeys.kContainFour: "Made up of 4 numbers only",
  LocalKeys.kOnlyDigits: "Made up of numbers only",
  LocalKeys.kKidDailyUse: 'Daily Usage Hours for the child',
  LocalKeys.kHour: "Hour",
  LocalKeys.kMinute: "Minute",
  LocalKeys.kAdvancedChooses: 'Advanced Choices',
  LocalKeys.kAreYou: 'Are You',
  LocalKeys.kYears: "Years",
  LocalKeys.kFatherMotherName: "Father/ Mother Name",
  LocalKeys.kRenewalAlert:
      "Please choose the appropriate package, knowing that the package is automatically renewed monthly or annually depending on the type of package chosen. You can cancel the subscription at any time by entering the subscriptions page and choosing to cancel the subscription.",
  LocalKeys.kNumberIsNotCorrect: "Incorrect Number, Try Again",
  LocalKeys.kJeelApp: "Jeel App",
  LocalKeys.kFollowKidReports: "Track your child's reports",
  LocalKeys.kFollowKidLearn: "Track all values your child has learned",
  LocalKeys.kOkey: "Okay",
  LocalKeys.kStartNow: "Start Now",
  LocalKeys.kAweasome: "Awesome",
  LocalKeys.kReadyToStartJeelJounary:
      "Are you ready to go with us on a Journey where you and your children have a lot of fun! We will provide your children time to have fun and improve their character with the Jeel family",
  LocalKeys.kTrackKidUse:
      "Track your child's activity on Jeel APP, how much time does he spend on the app? And When does he open it?, And Find out his answers results on every activity for each episode he watches.",
  LocalKeys.kReportsForParents:
      "Dear Father and Mother, for both of you we have jusoor section, your gateway of your child's world where you can find rich content of educational programs, and detailed reports about all episodes your child watches, and all values related to it.",
  LocalKeys.kExcuse: "Sorry!",
  LocalKeys.kCantUpdateLoginMethod:
      "We weren't able to update registration method",
  LocalKeys.kThankYou: "Thank You!",
  LocalKeys.kLoginMethodUpdated:
      "The registration method to your account has been changed",
  LocalKeys.kOtpSentToEmail: "To reset your Password, We sent you a link on",
  LocalKeys.kCheckYourEmail:
      "Please Check your E-mail, and follow instructions to reset your Password, then login again using your E-mail and new password",
  LocalKeys.kNoAccountWithThisEmail:
      "There is no account by this provided E-mail",
  LocalKeys.kCodeSent: "Code has been sent!",
  LocalKeys.kNoRecommendations: "No Recommendations",
  LocalKeys.kUserDoesNotExist:
      "This account has not been registered before. please register first",
  LocalKeys.kEmailAlreadyUsed:
      "This E-mail has been used before. Please Enter a new E-mail",
  LocalKeys.kCredAlreadyUsed:
      "This account has already been registered, use another account",
  LocalKeys.kWeakPassword:
      "Weak password, use a password containing symbols and letters",
  LocalKeys.kPhoneNotConnected:
      "The Phone is not connected to the Internet Please Try Again",
  LocalKeys.kTooManyRequests:
      "You have tried to enter many times, try again later",
  LocalKeys.kNewLogin:
      "It has been a long time since your last login Log in again",
  LocalKeys.kCantAddKid:
      "Something wrong, we weren't able to add another child, check your connection",
  LocalKeys.kUnsupportedExtension: "Unsupported attached file format",
  LocalKeys.kCantAccess: "Access to gallery has been denied",
  LocalKeys.kMaleChildCantAccess:
      "You cant access your favorite APP right now, ask your Parent to activate your account",
  LocalKeys.kFemaleChildCantAccess:
      "You cant access your favorite APP right now, ask your Parent to activate your account",
  LocalKeys.kJoinJeelFamily: "Join Jeel Family",
  LocalKeys.kOr: "OR",
  LocalKeys.kSubscripAndGetDiscount: 'Subscribe now and get a discount',
  LocalKeys.kTo60Percent: 'up to 60% ',
  LocalKeys.kForLimitedTime: "for a limited time!",
  LocalKeys.kAccount: 'Account ',
  LocalKeys.kEditInfo: "Edit Information",
  LocalKeys.kActivateAccount: "Activate Account",
  LocalKeys.kDisableAccount: 'Disable Account',
  LocalKeys.kDeleteAccount: 'Delete Account',
  LocalKeys.kWantDeleteAccount: "Would you like to delete ",
  LocalKeys.kAccountWillDeleted: "account will be deleted ",
  LocalKeys.kWithAllReports: " With all Activities reports and usage",
  LocalKeys.kDelete2: "Delete",
  LocalKeys.kConfirmAccountSuspend: "Confirm the child's account deactivation",
  LocalKeys.kToHisAccount: "from entering to his account?",
  LocalKeys.kConfirmSuspend: "Are you sure you want to restrict",
  LocalKeys.kDisable: "Deactivate",
  LocalKeys.kCantAddReview:
      "you are not be able to add a new review, and you can edit your previous review from APP Store",
  LocalKeys.kShareText:
      "Jeel App ... A world of Education and Entertainment for your children in plain standard Arabic Language\n Install it now!\n https://jeelapp.app.link/App",
  LocalKeys.kSuspended: "Disabled",
  LocalKeys.kActivated: "Active",
  LocalKeys.kAppNotUsedYet: "App has not been used yet",
  LocalKeys.kLastUse: "Last use",
  LocalKeys.kEducationalSection: "Educational Section",
  LocalKeys.kSignOut: "Log Out",
  LocalKeys.kShareApp: "Share App",
  LocalKeys.kReviewApp: "Rate App",
  LocalKeys.kAboutJeel: "About Jeel",
  LocalKeys.kJosoorEducationalSection: "Jusoor (The Educational Section)",
  LocalKeys.kPackageExpired:
      "your package has expired! Let's Renew your subscription... Jeel family is waiting for you",
  LocalKeys.kPackageWillEnd: "Your package will expire soon",
  LocalKeys.kCantAccessCamera: "Access to camera has been denied",
  LocalKeys.kRateDetails: "Evaluation Details",
  LocalKeys.kRecommendations: "Recommendations",
  LocalKeys.kNumberOfTimes: "Number of times",
  LocalKeys.kSolveActivity: "The activity Solution",
  LocalKeys.kWatching: "Watching",
  LocalKeys.kOverAllEvulation: "Evaluation",
  LocalKeys.kDetails: "Details",
  LocalKeys.kFavGame: "The Favorite Game",
  LocalKeys.kLastGame: "Last game your child has played",
  LocalKeys.kEpisodesDetails: "Episodes Details",
  LocalKeys.kFavRadio: "The Favorite Radio",
  LocalKeys.kLastRadio: "Last Radio your child has listened to",
  LocalKeys.kWatchedEpisodes: 'Watched Episodes',
  LocalKeys.kReport: "Reports",
  LocalKeys.kActivity: "Activities",
  LocalKeys.kUsage: "Usage",
  LocalKeys.kMinutes: "Minutes",
  LocalKeys.kTwoMintues: "Two Minutes",
  LocalKeys.kOneMintues: "One Minutes",
  LocalKeys.kFavEpisode: "The Favorite Episode",
  LocalKeys.kFavSeries: "The Favorite Series",
  LocalKeys.kFavSong: "The Favorite Song",
  LocalKeys.kFavStory: "The Favorite Story",
  LocalKeys.kLastSong: "Last Song your child has watched",
  LocalKeys.kOneTime: "One Time",
  LocalKeys.kTwoTime: "Two Times",
  LocalKeys.kTime: "Once",
  LocalKeys.kEduPapers: "Educational files",
  LocalKeys.kDevProgram: "Improvement Program",
  LocalKeys.kUntilToday: "Until Today",
  LocalKeys.kEditChildInfo: "Edit Child's Information",
  LocalKeys.kChildAge: "how old is he?",
  LocalKeys.kCopyWrite:
      "All Rights are reserved\n For Roots Integrated Company",
  LocalKeys.kTheSubscription: "Subscription",
  LocalKeys.kBackToApp: "Back to the App",
  LocalKeys.kChoosePaymentMethod: "Choose Payment Method",
  LocalKeys.kThrough: "Through",
  LocalKeys.kMoreDetails: ' More Details...',
  //"الإشتراك السنوي يوفر قيمة اشتراك 3 شهور",
  LocalKeys.kMonthly: "Monthly",
  LocalKeys.kYearly: "Annually",
  LocalKeys.kWeekly: "Weekly",
  LocalKeys.kReplace: "Instead of ",
  LocalKeys.kFawry: "Fawry",
  LocalKeys.kFawryCode:
      "A Code will be sent on your E-mail or your Phone, Take the Code and go to the nearest Fawry outlet for payment",
  LocalKeys.kAppleStore: "Apple Store",
  LocalKeys.kGoogleStore: "Google Store",
  LocalKeys.kWriteCardDetails:
      "Enter the Card Data for payment, and Enjoy  Jeel World",
  LocalKeys.kPaymentCard: "Payment Card",
  LocalKeys.kMadaCard: "Mada Card",
  LocalKeys.kHavePrePaidCard: "Do you have a prepaid card from Jeel?",
  LocalKeys.kDataSecurity:
      "Payment is processed through each different way possible for the security of your data",
  LocalKeys.kSubscripInJeel: "Subscribe in Jeel",
  LocalKeys.kPackageAutoRenew: "Automatic Package Renewal Activation",
  LocalKeys.kRenewDate: "Renewal Date",
  LocalKeys.kYouSubscriped: "You are now subscribed to",
  LocalKeys.kRenewPackage: "Pre-renewal package",
  LocalKeys.kPackageHistory: "History of previous subscriptions",
  LocalKeys.kOneAccount:
      "One account in Jeel open a world of fun and education for you and your children",
  LocalKeys.kJosoorBlogs:
      "Educational activities for the child after every episode",
  LocalKeys.kDailyReport: "View all daily usage reports",
  LocalKeys.kEduActivities: "View all jusoor's educational articles",
  LocalKeys.kEducationActivities: "Educational Activity",
  LocalKeys.kEduActivityHelpYou:
      "The educational activity will help you communicate the value better to your child.",
  LocalKeys.kEnjoyGamesSongs: "Enjoy all games and children songs",
  LocalKeys.kWatchallEpisodesStories: "You can watch all series and stories",
  LocalKeys.kOneAccountThreeKids: "One Account For 3 children",
  LocalKeys.kDeadlineDate: "Expiration Date",
  LocalKeys.kErrorInCancelation: "Error occurred during Cancellation!",
  LocalKeys.kCanAutoRenew:
      "You can activate the automatic renewal during subscription by the payment card!",
  LocalKeys.kWannaToCancelAutoRenew:
      "Would you like to cancel the Automatic Renewal?",
  LocalKeys.kUndo: "Cancel",
  LocalKeys.kWillCancelAutoRenew:
      "Automatic Renewal will be canceled, and if you want to Re-activate it, you have to Resubscribe ",
  LocalKeys.kPaymentError: "Error during payment process!",
  LocalKeys.kUnSuccessPayment: "Unsuccessful Payment Process",
  LocalKeys.kWhichEqual: "which equal, ",
  LocalKeys.kAlmost: "Almost ",
  LocalKeys.kCardNumberInvalid: "Incorrect Card Number",
  LocalKeys.kInternetConnection: "Please Check your Internet Connection",
  LocalKeys.kYouChooseToPay: "you choose to pay for a Subscription: ",
  LocalKeys.kEnterDataBelow: 'Enter the following data',
  LocalKeys.kConfirmPayment: "Payment Confirmation",
  LocalKeys.kCVV: "CVV",
  LocalKeys.kEnterCVV: "Enter CVV on the back of the credit card",
  LocalKeys.kNumbetIsInvalid: "Incorrect Number",
  LocalKeys.kEnterCardEndDate: "Enter card expiration date",
  LocalKeys.kCardNumber: "Card number",
  LocalKeys.kEnter16NumCard: "Enter the card number consisting of 16 digits",
  LocalKeys.kPersonalInfoUpdated: "Personal Information is updated",
  LocalKeys.kErrorInUpdateEmail: "Error in updating  your Email Information",
  LocalKeys.kCountry: "Country",
  LocalKeys.kDad: 'Father',
  LocalKeys.kMom: "Mother",
  LocalKeys.kEnterYourPassword: "Enter your Password",
  LocalKeys.kCurrentPassword: "Current Password",
  LocalKeys.kPasswordEditError: "Error while editing password",
  LocalKeys.kPasswordEdited: "Password has been changed",
  LocalKeys.kChildContentEdited: "Child's Content has been edited",
  LocalKeys.kConfirmationMessage: "Confirmation Message",
  LocalKeys.kContentWithMusic:
      "The content on the children's app will appear with music",
  LocalKeys.kContentWithoutMusic:
      "The Content on the child's app will appear without music",
  LocalKeys.kChildConfig: "Child's Content settings",
  LocalKeys.kChooseVersion:
      "Jeel App Content of Series, Songs, and Games is available with Music Version, and No Music Version.Choose Which Version, Would you like your child to watch?",
  LocalKeys.kNoFile: "No file Available",
  LocalKeys.kSubscripToEnjoy: "Subsribe to enjoy all of Jeel App Content",
  LocalKeys.kLetsDevelopOurChild: "lets improve our child skills",
  LocalKeys.kJeelEpisodes: "Jeel Episodes",
  LocalKeys.kJeelValues: 'Jeel Values',
  LocalKeys.kSongs: "Songs",
  LocalKeys.kJeelRadio: "Radio Jeel ",
  LocalKeys.kCategories: "Categories",
  LocalKeys.kEnjoyWithYourChild:
      "From all Jeel world heroes, you are your real child's hero Enjoy an amazing educational journey with you child, Jusoor will guide you during this journey with educational files that explain the episodes' value, and developmental programs that provide you with practical steps to raise the sound values and good behaviour, also Jusoor will let you know about your children's favourite series and heroes in order to discuss the episodes and characters with your children. And remember, your child always loves spending time with his/her real hero.",

  LocalKeys.kEpisodesInculdeValues: "Episodes including value ",
  LocalKeys.kJosoor: "Jusoor",
  LocalKeys.kShowEduValues: "You can search by values or episodes",
  LocalKeys.kStartYourJounary: 'Start your journey!',
  LocalKeys.kSong: "Song",
  LocalKeys.kDay: "Days",
  LocalKeys.kHours: "Hours",
  LocalKeys.kTheDay: "Today",
  LocalKeys.kLastResponse: "Last reply",
  LocalKeys.kLastResponseFrom: "Last reply since",
  LocalKeys.kMessage: "Message",
  LocalKeys.kSupportTeam: "Technical support team",
  LocalKeys.kProblemRecieved:
      "We have received your complaint, and we will reply as soon as possible",
  LocalKeys.kProblemType: "Type of problem",
  LocalKeys.kAddAddressAndTitleOfRequest:
      "Enter a title and a detailed description of your problem",
  LocalKeys.kAppBetterWithYou: "Our app is better with you!",
  LocalKeys.kWeSeekItBetter:
      "We strive to make your experience in Jeel APP perfect and fun, we are glad to receive your complaints and suggestions that you would like to find in our app",
  LocalKeys.kMessageAddress: 'Message title',
  LocalKeys.kMessageReason: 'Message Reason',
  LocalKeys.kMessageDetails: 'Message Details',
  LocalKeys.kWriteHere: "Write Here",
  LocalKeys.kAttachPic: 'Attach a Pichture',
  LocalKeys.kSendMessage: "Send",
  LocalKeys.kProblem: "Complaint",
  LocalKeys.kNewChild: "New Child",
  LocalKeys.kDeleteConfirmationTitleEnglish:
      'Are you sure you want to delete your account?',
  LocalKeys.kDeleteConfirmationTextEnglish:
      'By deleting your account, all your data will be removed, including your account information, children\'s information, and usage data. After deletion, You will no longer be able to log in to this account and you will need to create a new account to use the app.',
  LocalKeys.kEnteredWrongPasswordBro:
      "Incorrect password, my friend! Please ask your parents for the correct password",

  LocalKeys.kEnteredWrongPasswordGirl:
      "Incorrect password, my friend! Please ask your parents for the correct password",
  LocalKeys.kReadWithJeel: 'Read with Jeel',
  LocalKeys.kJeelGames: 'Jeel Games',
  LocalKeys.kNoGames: 'No Games Available',
  LocalKeys.kNoBooks: 'No Books Available',
  LocalKeys.kNoRadio: 'No Radio Available',
  LocalKeys.kJeelSeries: "Jeel Series",
  LocalKeys.kJeelSongs: 'Jeel Songs',
  LocalKeys.kJeelChants: 'Jeel Chants',
  LocalKeys.kTimeOutSeeYouTomorrowBoy:
      "Your time limit is up for today, see you tomorrow my friend",
  LocalKeys.kTimeOutSeeYouTomorrowGirl:
      "Your time limit is up for today, see you tomorrow my friend.",
  LocalKeys.kHowDoYouPreferAppContent: "How do you like Jeel's content",
  LocalKeys.kEnterFourNumbers: "Enter 4 digits",
  LocalKeys.kCanNotPay: "Unable to process payment",
  LocalKeys.kCongratulations: "Congratulations",
  LocalKeys.kNoInternetConnection: "No internet connection",
  LocalKeys.kConnectionFailed: "Error in connection",
  LocalKeys.kPaymentSuccess: "Payment processed successfully",
  LocalKeys.kWrongCredentials: "Error in data",
  LocalKeys.kCardInfo: "Card information",
  LocalKeys.kScanCard: "Scan the QR code on the card",
  LocalKeys.kOrEnterSubscriptionCode: "Or enter the subscribtion code here",
  LocalKeys.kSubscriptionCode: "Subscription code",
  LocalKeys.kWelcomeInJeelFamilyPrePaidSubscription:
      "Welcome to Jeel family! You are now subscribed by prepaid card from Jeel",
  LocalKeys.kLetsDiscoverJeelWorld: "Let's explore Jeel world!",
  LocalKeys.kEnterSubscriptionCode: "Enter The Subscription Code",
  LocalKeys.kWrongSubscriptionCode:
      "Sorry! Incorrect subscribtion code. Please check the code",
  LocalKeys.kSorryNoAvailableBooks: "Sorry, No Books Available!",
  LocalKeys.kPrepaidJeelCard: "Jeel Prepaid Card",
  LocalKeys.kThroughMadaCard: " by MADA Card",
  LocalKeys.kCardExpired: "This Card is expired",
  LocalKeys.kKidInvalidAge: "The Child age can not be Zero!",
  LocalKeys.kTotalWeekUsageTime: "Total usage time this week",
  LocalKeys.kAverageDailyUse: "Average daily use",
  LocalKeys.kChildDayUse: "Your child's use throughout the day",
  LocalKeys.kLastSevenDaysChildActivitiesMessage:
      "It seems that your child has not done any of these activities in the last seven days! Encourage your child to answer the activities of the episodes he watches to get the most out of them.",

  LocalKeys.kLastSevenDaysChildRadioWatchingMessage:
      "It seems that your child has not watched any of the content of Radio Jeel in the last seven days! Encourage your child to navigate all sections of the app to get the most out of it.",
  LocalKeys.kLastSevenDaysChildSeriesWatchingMessage:
      "It seems that your child has not watched any of the content of the Series in the last seven days! Encourage your child to navigate all sections of the app to get the most out of it.",
  LocalKeys.kLastSevenDaysChildGamesWatchingMessage:
      "It seems that your child has not Play in the last seven days! Encourage your child to navigate all sections of the app to get the most out of it.",
  LocalKeys.kLastSevenDaysChildDiscoverWatchingMessage:
      "It seems that your child has not watched any of the content of learning & skills with Jeel in the last seven days! Encourage your child to navigate all sections of the app to get the most out of it.",
  LocalKeys.kLastSevenDaysChildSongsWatchingMessage:
      "It seems that your child has not watched any of the content of the Songs in the last seven days! Encourage your child to navigate all sections of the app to get the most out of it.",
  LocalKeys.kLastSevenDaysChildStoriesWatchingMessage:
      "It seems that your child has not watched any of the content of The Stories in the last seven days! Encourage your child to navigate all sections of the app to get the most out of it.",
  LocalKeys.kTheSeries: "Series",
  LocalKeys.kTheStories: "Stories",
  LocalKeys.kTheChants: "Chants",
  LocalKeys.kTheSongs: "Songs",
  LocalKeys.kAddReply: "Add Reply",
  LocalKeys.kEditAccountInfo: "Edit Account Info",
  LocalKeys.kOldPassword: "Old Password",
  LocalKeys.kIntellectualPropertyNotice: "Intellectual Property Notice",
  LocalKeys.kDisclaimerOfLiability: "Disclaimer of Liability",
  LocalKeys.kToGames: "To Games",
  LocalKeys.kRetryPlayAndLearn: "Retry Play and Learn",
  LocalKeys.kContinueWatching: "Continue Watching",
  LocalKeys.kChangeLang: "Change App Language",
  LocalKeys.kChooseLang: "Please choose the application language you want.",
  LocalKeys.kArabic: "اللغة العربية",
  LocalKeys.kEnglish: "English",
  LocalKeys.kSeriesActivities: "Series Activities",
  LocalKeys.kStoriesActivities: "Stories Activities",
  LocalKeys.kDiscoverActivities: "Learning & skills Activities",
  LocalKeys.kChantsActivities: "Chants Activities",
  LocalKeys.kSongsActivities: "Songs Activities",
  LocalKeys.kPuzzle: "Puzzle",
  LocalKeys.kPainting: "Painting",
  LocalKeys.kDragAndDrop: "Drag and Drop",
  LocalKeys.kPlayAndLearn: "Play and learn",
  LocalKeys.kYourChildrenReports: "Your children's reports",
  LocalKeys.kYourChildren: "Your children",
  LocalKeys.kEditChildrenInfo: "Edit Children's Info",
  LocalKeys.kWatchs: "Watch",
  LocalKeys.kMoreValues: "more values",
  LocalKeys.kWatchMore: "Watch More",
  LocalKeys.kWatchAllEpisodes: "Watch all episodes' values",
  LocalKeys.kSelectCats: "Select from categories to watch values inside",
  LocalKeys.kView: "View",
  LocalKeys.kAllActivityCount: "activity",
  LocalKeys.kWelcomeTo: "Welcome, ",
  LocalKeys.kInArticle: "in Articles",
  LocalKeys.kYouWillFndMoreArticles:
      "We are sure that you will find lots of articles you will like. ",
  LocalKeys.kSubscribeToPlan: "Subscribe to our monthly plan, See the benefits",
  LocalKeys.kSubscribeBenefits: "Benefits",
  LocalKeys.kEditing: "Editing",
  LocalKeys.kChooseChildYouWantEditHisData:
      "Choose the child whose data you want to edit.",
  LocalKeys.kAddAnotherChild: "Add another child",
  LocalKeys.kAddYourChildDetails:
      "Please add your child's details to personalize the experience and have more control.",
  LocalKeys.kTheMinutes: "Minutes",
  LocalKeys.kModified: "Modified",
  LocalKeys.kChangeImage: "Change image",
  LocalKeys.kTakeImageFromCamera: "take a picture from the camera",
  LocalKeys.kUploadImageForChild: "Upload a personal photo of your child",
  LocalKeys.kYouCanAddPasswordAndControlTheDuration:
      "You can add a password and control the duration of daily use for the child.",
  LocalKeys.kFatherInfo: "Father Info",
  LocalKeys.kMotherInfo: "Mother Info",
  LocalKeys.kSideMenu: "Menu",
  LocalKeys.kSubscriptionEnded:
      "Your plan has expired, you can subscribe again.",
  LocalKeys.kToFinishPlan: "left until your plan expired.",
  LocalKeys.kRemain: "There are",
  LocalKeys.kSeePlan: "See Details",
  LocalKeys.kGoBack: "Go back",
  LocalKeys.kContentControl: "Content Control",
  LocalKeys.kEduJosoorParent: "Parent Educational Section(Jusoor)",
  LocalKeys.kEduJosoorParentBenefits:
      "Parent Educational Section(Jusoor) Benefits",
  LocalKeys.kEduJosoorParentHero:
      "Among the heroes of a generation, you are the true hero of your child. Learn about the advantages of Jusoor.",
  LocalKeys.kNext: "Next",
  LocalKeys.kYouSelected: "You've selected, ",

  LocalKeys.kAddYourChildNow: "Add your child now",
  LocalKeys.kAddYourChildInfo: "Add your child's info",
  LocalKeys.kSelectPictureOrUploadPicture:
      "Choose a photo of your child or upload a personal photo of him",
  LocalKeys.kAddNewChild: "Add new child",
  LocalKeys.kItIsBoy: "He is boy",
  LocalKeys.kSheIsGirl: "She is girl",
  LocalKeys.kUploadpictureForChild: "Upload Image for child",
  LocalKeys.kAllFieldRequired: "All fields required",
  LocalKeys.kSixPm: "6pm",
  LocalKeys.kSixAm: "6am",
  LocalKeys.kTwelvePm: "12pm",
  LocalKeys.kTwelveAm: "12am",
  LocalKeys.kSubscribeNow: "Subscribe",
  LocalKeys.kYouSureLogout: "Are you sure to logout?",
  LocalKeys.kWaitWantToLogout: "Wait a minute, do you want to logout?",
  LocalKeys.kYesLogout: "Yes, logout",
  LocalKeys.kNoThankyou: "No, Thank you",
  LocalKeys.kCloseWindow: "Close Window",
  LocalKeys.kMainValue: "Core values",
  LocalKeys.kMainScreen: "Main",
  LocalKeys.kSubValue: "Subvalues",
  LocalKeys.kInsideValueEduDev:
      "Within each value are educational seminars, papers, and a development program.",
  LocalKeys.kLearnValueDev:
      "Learn more about value, and develop it for your child",
  LocalKeys.kWhatValue: "What is the value of",
  LocalKeys.kLearnedEpisode: "learned from this episode?",
  LocalKeys.kHoldValue: "Which hold value of",
  LocalKeys.kEpisodeIntro: "ُEpisode Intro",

  LocalKeys.kHereAppears: "Here appears the most important",
  LocalKeys.kYourChildHasSolved: "that your child has solved",

  LocalKeys.kActivityDetails: "Activity details",
  LocalKeys.kChooseGames: "Great, choose now from the games",
  LocalKeys.kTypeOfCreativity:
      "What is the value of creativity learned from this episode?",
  LocalKeys.kOverallEvaluation: "Evaluation of activity",

  LocalKeys.kEducationalActivity: "Educational activity",
  LocalKeys.kTheEducationalActivityWillHelpYou:
      "An educational activity will help you communicate the value better to your child.",
  LocalKeys.kViews: "Views",
  LocalKeys.kHereShowViews: "Here shows the views of",
  LocalKeys.kYourChildHasWatched: " your child has watched in detail.",
  LocalKeys.kYourChildHasPracticed: "your child has practiced in detail.",

  LocalKeys.kAll: "All",
  LocalKeys.kGames: "Games",
  LocalKeys.kListening: "Listening",
  LocalKeys.kTheRadio: "Radio",
  LocalKeys.kHereShownListeningRadioYouChildHasHeard:
      "Here the radio listening that your child heard is shown in detail",
  LocalKeys.kViewDetails: "Watching details",
  LocalKeys.kWatchVideo: "Watch video",
  LocalKeys.kSubscribeNowAndEnjoy:
      "Subscribe now and enjoy the benefits of the Jeel application!",
  LocalKeys.kBySubScribeToJeel:
      "By subscribing to Jeel, a world of fun and benefit will open up for you and your children.",
  LocalKeys.kInvestInYourChild:
      "Invest in your children for a better future for them.",
  LocalKeys.kSubscribeInEducationalSection:
      "Subscribe to the best educational application for your children",

  LocalKeys.kSelect: "You choice",
  LocalKeys.kYouWillPay: "You will pay",
  LocalKeys.kForAWeek: "For a week",
  LocalKeys.kForAMonth: "For a month",
  LocalKeys.kForAYear: "For a year",
  LocalKeys.kChangePackage: "Change package",
  LocalKeys.kSelectPayMethod: "Select payment method",
  LocalKeys.kSelectPayMethodSuitedForYou:
      "Please choose the payment method that suits you.",
  LocalKeys.kPayNow: "Pay now",
  LocalKeys.kYearlyPackage: "Annual package",
  LocalKeys.kMonthlyPackage: "Monthly package",
  LocalKeys.kWeeklyPackage: "Weekly package",
  LocalKeys.kAbout: "About",
  LocalKeys.kEnjoyGames: 'Enjoy the latest generation games.',
  LocalKeys.kLearnEnjoyGames: 'Learn and have fun with Jeel games',
  LocalKeys.kListenSongsAnashees: 'Learn and sing with Jeel Songs.',
  LocalKeys.kSongsAnasheed: 'Enjoy Jeel Songs',
  LocalKeys.kRadioJeelEnjoy: 'Enjoy Radio Jeel ',
  LocalKeys.kLearnEnjoyRadio: 'Learn and sing with Radio Jeel ',
  LocalKeys.kSelectedMethod: "Selected method",
  LocalKeys.kChoose: "select",
  LocalKeys.kChoosePackage: "Select package",
  LocalKeys.kAutomaticallyRenewed: "Package Auto-renewal",
  LocalKeys.kSelectSuitedPackage: "Choose the package that suits you!",
  LocalKeys.kPleaseSelectFromMultiplePackage:
      "Please choose from the many packages we offer you.",
  LocalKeys.kYourSubscription: "Your subscriptions",
  LocalKeys.kSubscripThrough: "Subscribe via",
  LocalKeys.kYouSubscripedSuccessfuly:
      "You have successfully subscribed to the annual package",
  LocalKeys.kWishHappyExperience:
      "We wish you an enjoyable experience for you and your children.",
  LocalKeys.kHomePage: "Home page",
  LocalKeys.kSeriesEpisodes: "Series ُEpisodes",
  LocalKeys.kSelectEpisodeShowValue: "Click on the episode to see the values.",
  LocalKeys.kThePackageRenewWhenTheCurrentExpired:
      "The package will be renewed when the current package period expires on",
  LocalKeys.kChangeCategoris: "Categories",

  LocalKeys.kSubscribeWithUs: "Sign in",
  LocalKeys.kChooseTypeYouPrefer: "Choose the type you prefer for the content",
  LocalKeys.kWeHaveTwoTypeOfContent:
      "We have two type of the content with music and without music.",
  LocalKeys.kWithMusic: "With music",
  LocalKeys.kWithOutMusic: "With out music",
  LocalKeys.kChildApp: "Child app",

  LocalKeys.kCreateAccount: "Create account",
  LocalKeys.kSimpleStepsToJoinJeel:
      "Simple steps Separate you to enter the world of generation.",
  LocalKeys.kStepOne: "Step one",
  LocalKeys.kStepTwo: "Step two",
  LocalKeys.kLastStep: "Last step",
  LocalKeys.kSearchWithWords: "Search with words",
  LocalKeys.kWelcomeInJeelWorld:
      "Welcome back to the world of jeel, please enter your details.",
  LocalKeys.kChangeUser: "Change user",

  LocalKeys.kGreatLoginSuccessfuly:
      "Great, registration was successfully completed",
  LocalKeys.kLetsGoToParentApp: "Log in to the parent app and add your kids.",
  LocalKeys.kYourAccountsInJeel: "Your accounts in a Jeel",
  LocalKeys.kParentAccount: "Parent account",
  LocalKeys.kChildAccount: "Child accounts",
  LocalKeys.kWelcome: "Welcome",
  LocalKeys.kMore: "More",
  LocalKeys.kEnjoyRead: 'Enjoy the latest generation book.',
  LocalKeys.kLearnEnjoyRead: 'Learn and have fun with Jeel books',
  LocalKeys.kShowLess: "Show less",
  LocalKeys.kShowMore: "Show more",
  LocalKeys.kWhatNext: "What is next?",
  LocalKeys.kWantToEnjoyJeel:
      "Would you like to enjoy the rest of the app? Ask your guardian to subscribe to the application",
  LocalKeys.kWantToEnjoyJeelParent:
      "Would you like to enjoy the rest of the app?",
  LocalKeys.kWantToSubscribeJoinJeelParent:
      'Would you like to subscribe and join the Jeel family?',
  LocalKeys.kPages: 'Pages',
  LocalKeys.kPayment: "Payment",
  LocalKeys.kSubscriptionPolicy: "Subscriptions controlled by ",
  LocalKeys.kSubscriptionTerms: "Privacy & Policy",
  LocalKeys.kLoading: "Loading...",
  LocalKeys.kChildHasDeleted: "The account has been successfully deleted",
  LocalKeys.kNoActivitiesFound: "No Activities Found!",
  LocalKeys.kPractice: "Practice",
  LocalKeys.kPractices: "Practices",
  LocalKeys.kAllSections: "All sections",
  LocalKeys.kSummaryUsageTime: "Summary of usage times",
  LocalKeys.kEducationSystem: "Education section",
  LocalKeys.kValueCreativity: "The value of creativity",
  LocalKeys.kEpisodeIncludeActivity: "Episodes include creativity",
};
